Updates
XoopsModules25x/backpack pull request #3
Opened 2020-11-06 09:25 UTC by mambax7

2020-11-06 09:28 UTC, mambax7 commented
@montuy337513, please take a look and test. 
I've sent you an invitation to the team. Once you accept it, you'll be able to merge the changes here, once you test them.

2020-11-06 09:37 UTC, montuy337513 commented
@mambax7 , okay, I'm testing the changes this weekend

2020-11-06 23:15 UTC, zyspec requested changes
I did a quick code read.... I installed your version of the module and did a cursory check for errors (but did not invoke backup/restore) just to make sure that installing the module didn't crash the system.

2020-11-06 23:15 UTC, zyspec commented on admin/admin_footer.php
> +     . '/xoopsmicrobutton.gif" alt="Xoops" title="Xoops"></a>'
XOOPS is an acronym, recommend all caps
```suggestion
     . '/xoopsmicrobutton.gif" alt="XOOPS" title="XOOPS"></a>'
```

2020-11-06 23:15 UTC, zyspec commented on admin/admin_footer.php
> +     . '  <div class="center smallsmall italic pad5"> ce module est maintenu par <a href="https://store.chg-web.com" rel="external">Cedric MONTUY CHG-WEB</a>'
Default should be English - should really be moved to language file
```suggestion
     . '  <div class="center smallsmall italic pad5"> this module maintained by <a href="https://store.chg-web.com" rel="external">Cedric MONTUY CHG-WEB</a>'

2020-11-06 23:15 UTC, zyspec commented on admin/admin_header.php
> +global $xoopsModule;
Recommend deleting this line and replacing occurrances of `$xoopsModule` with `$GLOBALS['xoopsModule']`

2020-11-06 23:15 UTC, zyspec commented on admin/admin_header.php
> +xoops_loadLanguage('modinfo', $thisModuleDir);
use $adminObject instead:
```suggestion
$adminObject->loadLanguage('admin');
$adminObject->loadLanguage('modinfo');

2020-11-06 23:15 UTC, zyspec commented on admin/admin_header.php
> +        exit();
can delete `exit();`
```suggestion
```

2020-11-06 23:15 UTC, zyspec commented on admin/admin_header.php
> +    exit();
can delete `exit();`
```suggestion
```

2020-11-06 23:15 UTC, zyspec commented on admin/adminmenu.php
> +<!--/* Nice button styles */-->
Obviously it would be 'better' to move this to a css file instead of being hard coded here.

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +    if (DEBUG !== 0) {
Yoda conditional
```suggestion
    if (0 !== DEBUG) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +            for ($i = 0; $i < $iMax; $i++) {
for consistency and execution speed
```suggestion
            for ($i = 0; $i < $iMax; ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +    if (DEBUG) {
for consistency
```suggestion
    if (0 !== DEBUG) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +    if (DEBUG) {
for consistency
```suggestion
    if (0 !== DEBUG) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +        for ($i = 0;  $i < $iMax; $i++) {
for consistency and execution speed
```suggestion
        for ($i = 0; $i < $iMax; ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +            if (DEBUG) {
for consistency
```suggestion
            if (0 !== DEBUG) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +        for ($i = 0; $i < mysqli_num_fields($query_res); $i++) {
for consistency and execution speed
```suggestion
        $query_num = mysqli_num_fields($query_res);
        for ($i = 0; $i < $query_num); ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +        $dump_line++;
execution speed
```suggestion
        ++$dump_line;
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +    $download_count++;
for consistency and execution speed
```suggestion
    ++$download_count;
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.inc.php
> +    $q = 'LOCK TABLES';
It would seem to me that this function should check to make sure $tablename_array is an array and  isn't empty before doing the SQL query

2020-11-06 23:15 UTC, zyspec commented on admin/backup.ini.php
> +              . '/xoopsmicrobutton.gif" alt="xoops" title="xoops"></a>'
XOOPS is an acronym, should be in all caps
```suggestion
              . '/xoopsmicrobutton.gif" alt="XOOPS" title="XOOPS"></a>'
```

2020-11-06 23:15 UTC, zyspec commented on admin/backup.ini.php
> +              . '  <div class="center smallsmall italic pad5"> ce module est maintenu par <a href="https://store.chg-web.com" rel="external">Cedric MONTUY CHG-WEB</a>'
text should default to English - recommend moving string to language file
```suggestion
              . '  <div class="center smallsmall italic pad5"> this module is maintained by <a href="https://store.chg-web.com" rel="external">Cedric MONTUY CHG-WEB</a>'
```

2020-11-06 23:15 UTC, zyspec commented on admin/download.php
> +//}
These three (3) lines are duplicates of the following lines so these should just be deleted.
```suggestion
```

2020-11-06 23:15 UTC, zyspec commented on admin/download.php
> +//
```suggestion
// @TODO - add check for Microsoft Edge browser
//
```

2020-11-06 23:15 UTC, zyspec commented on admin/index2.php
> +    $fetch = $f[0];
should validate that fetch_array returned valid results (ie. not NULL)
```suggestion
    $fetch = NULL !== $f ? $f[0] : NULL;
```

2020-11-06 23:15 UTC, zyspec commented on admin/index2.php
> +           . '<label for="sql">text</label>&nbsp;&nbsp</td></tr>';
These <label> elements need to be reworked. The 'for' attribute should be for the 'id' of the <input> element it is attached to.  For example I believe the `<label for="gz">` should be `<label for="gzip">`

2020-11-06 23:15 UTC, zyspec commented on admin/index2.php
> +        for ($i = 0; $i < $num_tables; $i++) {
for consistency and execution speed
```suggestion
        for ($i = 0; $i < $num_tables; ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/index2.php
> +            for ($i = 0; $i < $num_tables; $i++) {
for consistency and execution speed
```suggestion
            for ($i = 0; $i < $num_tables; ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/index2.php
> +                        $j++;
for consistency and execution speed
```suggestion
                        ++j;
```

2020-11-06 23:15 UTC, zyspec commented on admin/index2.php
> +            for ($i = 0; $i < $num_tables; $i++) {
for consistency and execution speed
```suggestion
            for ($i = 0; $i < $num_tables; ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on admin/index2.php
> +            for ($i = 0;  $i < $iMax; $i++) {
for consistency and execution speed
```suggestion
            for ($i = 0; $i < $iMax; ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on hook_cron.php
> +    for ($i = 0; $i < $num_tables; $i++) {
for consistency and execution speed
```suggestion
    for ($i = 0; $i < $num_tables; ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on class/class.backpack.php
> +            for ($i = 0;  $i < $iMax; $i++) {
for consistency and execution speed
```suggestion
            for ($i = 0; $i < $iMax; ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on class/class.backpack.php
> +            for ($i = 0; $i < $xoopsDB->getFieldsNum($this->query_res); $i++) {
for consistency and execution speed
```suggestion
            for ($i = 0; $i < $xoopsDB->getFieldsNum($this->query_res); ++$i) {
```

2020-11-06 23:15 UTC, zyspec commented on class/class.backpack.php
> +        global $xoopsDB;
Should make sure that `$tablename_array` is an array and is not empty.
```suggestion
        global $xoopsDB;
        if (!is_array($tablename_array) || empty($tablename_array)) {
            return false;
        }
```

2020-11-07 01:04 UTC, mambax7 commented on admin/admin_header.php
> +xoops_loadLanguage('modinfo', $thisModuleDir);
You mean, $helper, and not $adminObject, right? 
I was using xoops_loadLanguage(), because I didn't want yet to add the Helper class and namespaces.

2020-11-07 10:39 UTC, mambax7 commented on admin/adminmenu.php
> +<!--/* Nice button styles */-->
Actually adminmenu.php is not needed anymore, so I simply deleted it

2020-11-07 10:40 UTC, mambax7 commented on admin/backup.inc.php
> +    $q = 'LOCK TABLES';
This file is not used, so I deleted it

2020-11-09 08:52 UTC, merged